CREATE TABLE TBL_FLOWER	(
	FLOWER_NAME VARCHAR2(1000),
	FLOWER_COLOR VARCHAR2(1000),
	FLOWER_PRICE NUMBER,
	FLOWER_DATE DATE,
	FLOWER_STOCK NUMBER,
	FLOWER_DISCOUNT NUMBER,
	CONSTRAINT PK_FLOWER PRIMARY KEY(FLOWER_NAME, FLOWER_COLOR)
);

CREATE TABLE TBL_POT (
	POT_NUMBER NUMBER CONSTRAINT PK_POT PRIMARY KEY,
	POT_COLOR VARCHAR2(1000),
	POT_SHAPE VARCHAR2(1000),
	POT_PRICE NUMBER,
	POT_STOCK NUMBER,
	FLOWER_NAME VARCHAR2(1000),
	FLOWER_COLOR VARCHAR2(1000),
	CONSTRAINT FK_POT FOREIGN KEY(FLOWER_NAME, FLOWER_COLOR)
	REFERENCES TBL_FLOWER(FLOWER_NAME, FLOWER_COLOR)
);

CREATE TABLE TBL_GUARDIAN (
	GUARDIAN_PHONE VARCHAR2(1000) CONSTRAINT PK_GUARDIAN PRIMARY KEY,
	GUARDIAN_NAME VARCHAR2(1000),
	GUARDIAN_AGE NUMBER,
	GUARDIAN_ADDRESS VARCHAR2(1000)
);

CREATE TABLE TBL_ANIMALS (
	ANIMALS_NUMBER NUMBER CONSTRAINT PK_ANIMALS PRIMARY KEY,
	ANIMALS_KIND VARCHAR2(1000),
	ANIMALS_NAME VARCHAR2(1000),
	ANIMALS_AGE NUMBER,
	ANIMALS_DISEASE VARCHAR2(1000),
	GUARDIAN_PHONE VARCHAR2(1000),
	CONSTRAINT FK_ANIMALS FOREIGN KEY(GUARDIAN_PHONE)
	REFERENCES TBL_GUARDIAN(GUARDIAN_PHONE)
);

/*TBL_MEMBER 테이블에 정보 추가*/
SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER (MEMBER_NAME, MEMBER_AGE)
VALUES('홍길동', 20);

UPDATE TBL_MEMBER
SET MEMBER_NAME = '이순신'
WHERE MEMBER_AGE > 21;

DELETE FROM TBL_MEMBER
WHERE MEMBER_NAME = '이순신';
