/*축구 선수들 중에서 각 팀별로 키가 가장 큰 선수들의 전체 정보 조회*/
SELECT TEMA_ID, MAX(HEIGHT) FROM PLAYER
GROUP BY TEAM_ID;

SELECT * FROM
(
	SELECT TEMA_ID, MAX(HEIGHT) MAX_HEIGHT FROM PLAYER
	GROUP BY TEAM_ID
)P1
JOIN PLAYER P2
ON P1.TEAM_ID = P2.TEAM_ID AND P1.MAX_HEIGHT = P2.HEIGHT;

/*위 문제에서 JOIN을 사용하지 않고 조회
 * (A, B) IN (C,D) : A = C AND B = D*/
SELECT * FROM PLAYER
WHERE (TEAM_ID, HEIGHT) IN
(
	SELECT TEMA_ID, MAX(HEIGHT) MAX_HEIGHT FROM PLAYER
	GROUP BY TEAM_ID
);

/*EMP 테이블의 SAL을 SALGRADE 등급으로 나누기*/
SELECT E.ENAME, SAL, S.GRADE FROM EMP E JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

/*EMP 테이블에서 각 사원의 매니저 이름 조회*/
SELECT * FROM EMP;

SELECT E1.ENAME 사원, E2.ENAME 매니저
FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO;

/*브론즈*/
/*PLAYER 테이블에서 키가 NULL인 선수들은 키를 170으로 변경하여 평균 구하기(NULL포함)*/
SELECT PLAYER_NAME, NVL(HEIGHT, 170) HEIGHT FROM PLAYER;

/*실버*/
/*PLAYER 테이블에서 팀 별 최대 몸무게*/
SELECT TEAM_ID, MAX(HEIGHT) HEIGHT FROM PLAYER
GROUP BY TEAM_ID;

/*골드*/
/*AVG 함수를 쓰지 않고 PLAYER 테이블에서 선수들의 평균 키 구하기(NULL 미포함)*/
SELECT SUM(HEIGHT) / COUNT(HEIGHT) FROM PLAYER;

/*플래티넘*/
/*DEPT 테이블의 LOC별 평균 급여를 반올림한 값과 각 LOC별 SAL 총 합을 조회*/
/*ROUND(값, 소수점 자리수)*/
SELECT LOC, ROUND(AVG(SAL), 2) "AVG", SUM(SAL) "SUM" FROM DEPT D JOIN EMP E
GROUP BY LOC;

/*다이아*/
/*PLAYER 테이블에서 팀별 최대 몸무게인 선수 전체 정보 검색*/
SELECT * FROM
(
	SELECT TEAM_ID, MAX(WEIGHT) MAX WEIGHT FROM PLAYER
	GROUP BY TEAM_ID
)P1
JOIN PLAYER P2
ON P1.TEAM_ID = P2.TEAM_ID AND P1.MAX_WEIGHT = P2.WEIGHT;

/*마스터*/
/*EMP 테이블에서 HIREDATE가 FORD의 입사년도와 같은 사원 전체 정보 조회*/
SELECT * FROM EMP
WHERE TO_CHAR(HIREDATE, 'YYYY') = (SELECT TO_CHAR(HIREDATE, 'YYYY' FROM EMP WHERE ENAME = 'FORD');

/*VIEW*/
/*PLAYER 테이블에서 나이 컬럼을 추가한 뷰 만들기*/
CREATE VIEW VIEW_PLAYER AS
SELECT P.*, ROUND(SYSDATE - BIRTH_DATE) / 365) AGE FROM PLAYER P;

SELECT AGE FROM VIEW_PLAYER;

/*EMPLOYEES 테이블에서 사원 이름과 그 사원의 매니저 이름이 있는 VIEW 만들기*/
/*FIRST_NAME과 LAST_NAME은 CONCATENATION을 사용하여 연결한다*/
SELECT










