/*TBL_STUDENT 테이블 CRUD*/
CREATE SEQUENCE SEQ_STUDENT;

INSERT INTO TBL_STUDENT
(STUDENT_NUMBER, STUDENT_ID, STUDENT_NAME, STUDENT_MAJOR, STUDENT_GENDER, STUDENT_BIRTH)
VALUES(SEQ_STUDENT.NEXTVAL, 'HGD', '홍길동', '공간정보공학과', 'M', '2001-05-05');

SELECT * FROM TBL_STUDENT;

UPDATE TBL_STUDENT
SET STUDENT_GENDER='M'
WHERE STUDENT_NUMBER=1;

CREATE SEQUENCE SEQ_POT;

SELECT * FROM TBL_FLOWER;
SELECT * FROM TBL_POT;

INSERT INTO TBL_FLOWER
(FLOWER_NAME, FLOWER_COLOR, FLOWER_PRICE, FLOWER_DATE, FLOWER_STOCK, FLOWER_DISCOUNT)
VALUES('장미', '흰색', 7000, SYSDATE + 5, 10, 0);

INSERT INTO TBL_POT
(POT_NUMBER, POT_COLOR, POT_SHAPE, POT_PRICE, POT_STOCK, FLOWER_NAME, FLOWER_COLOR)
VALUES(SEQ_POT.NEXTVAL, '파란색', '직사각형', 23000, 5, '장미', '흰색');
/*자식에서 참조중인 데이터는 부모에서 수정이 불가능하다
 * 이럴 경우 자식에서 참조중인 데이터를 NULL로 변경시키고
 * 부모의 데이터를 수정한 뒤 자식의 데이터를 수정한다(잘 안쓰는 방법)*/
UPDATE TBL_FLOWER
SET FLOWER_NAME = '안개꽃'
WHERE FLOWER_NAME = '장미' AND FLOWER_COLOR = '흰색';

UPDATE TBL_POT
SET FLOWER_NAME = '안개꽃'
WHERE POT_NUMBER = 4;

/*자식의 FK를 변경할 때에는 부모에 존재하는 값으로 변경해야 하고
 * 만약 부모에 없는 값으로 변경해야 할 때에는 부모에 먼저 INSERT를 진행한 뒤
 * 자식 FK를 수정하도록 한다*/

INSERT INTO TBL_FLOWER
VALUES('장미', '흰색', '7500', SYSDATE + 7, 5, 0);

UPDATE TBL_FLOWER
SET FLOWER_NAME = '안개꽃'
WHERE FLOWER_NAME = '장미' AND FLOWER_COLOR = '흰색';

UPDATE TBL_POT
SET FLOWER_NAME = '장미'
WHERE POT_NUMBER = 4;

/*삭제*/
DELETE FROM TBL_POT
WHERE FLOWER_NAME = '해바라기' AND FLOWER_COLOR = '노란색';

DELETE FROM TBL_FLOWER
WHERE FLOWER_NAME = '해바라기' AND FLOWER_COLOR = '노란색';

DELETE FROM TBL_FLOWER
WHERE FLOWER_NAME = '장미' AND FLOWER_COLOR = '흰색';

ALTER TABLE TBL_POT DROP CONSTRAINT FK_POT;
ALTER TABLE TBL_POT ADD CONSTRAINT FK_POT FOREIGN KEY(FLOWER_NAME, FLOWER_COLOR)
REFERENCES TBL_FLOWER(FLOWER_NAME, FLOWER_COLOR) ON DELETE CASCADE;











